python3 ./getucardata.py
python3 ./northatlanticdata.py
python3 ./northpacificdata.py
python3 ./northindiandata.py
python3 ./southernhemispheredata.py
python3 ./getclimo.py
python3 ./northatlanticgraph.py
python3 ./northeastpacificgraph.py
python3 ./northwestpacificgraph.py
python3 ./northindiangraph.py
python3 ./northernhemispheregraph.py
python3 ./southindiangraph.py
python3 ./southpacificgraph.py
python3 ./southernhemispheregraph.py
